### ISSUE TITLE
Get error while Installing yolo34py-gpu 

### ISSUE THREAD

**Issue by fspider** [madhawav/YOLO3-4-Py#105]
Cuda 10.0, Cudnn 7.6.5, Tensorflow is working on this Ubuntu 18.04 system
And i tried to install yolo34py-gpu but got this error after downloading
What is the reason and how can i solve this problem?
==============================================

ERROR: Command errored out with exit status 1:
     command: /home/ubuntu/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-z5behrbg/yolo34py-gpu/setup.py'"'"'; __file__='"'"'/tmp/pip-install-z5behrbg/yolo34py-gpu/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-z5behrbg/yolo34py-gpu/pip-egg-info
         cwd: /tmp/pip-install-z5behrbg/yolo34py-gpu/
    Complete output (91 lines):
    INFO:root:Selected Darknet Branch: yolo34py-intergration-nocv from Darknet Fork 'https://github.com/madhawav/darknet/'
    ERROR: Exception:
    Traceback (most recent call last):
      File "/home/ubuntu/venv/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 425, in _error_catcher
        yield
      File "/home/ubuntu/venv/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 507, in read
        data = self._fp.read(amt) if not fp_closed else b""
      File "/home/ubuntu/venv/lib/python3.6/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read
        data = self.__fp.read(amt)
      File "/usr/lib/python3.6/http/client.py", line 459, in read
        n = self.readinto(b)
      File "/usr/lib/python3.6/http/client.py", line 503, in readinto
        n = self.fp.readinto(b)
      File "/usr/lib/python3.6/socket.py", line 586, in readinto
        return self._sock.recv_into(b)
      File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
        return self.read(nbytes, buffer)
      File "/usr/lib/python3.6/ssl.py", line 874, in read
        return self._sslobj.read(len, buffer)
      File "/usr/lib/python3.6/ssl.py", line 631, in read
        v = self._sslobj.read(len, buffer)
    socket.timeout: The read operation timed out
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/ubuntu/venv/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
        status = self.run(options, args)
      File "/home/ubuntu/venv/lib/python3.6/site-packages/pip/_internal/commands/wheel.py", line 158, in run
        resolver.resolve(requirement_set)
      File "/home/ubuntu/venv/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 201, in resolve
        self._resolve_one(requirement_set, req)
      File "/home/ubuntu/venv/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
        abstract_dist = self._get_abstract_dist_for(req_to_install)
      File "/home/ubuntu/venv/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 313, in _get_abstract_dist_for
        req, self.session, self.finder, self.require_hashes
      File "/home/ubuntu/venv/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 194, in prepare_linked_requirement
        progress_bar=self.progress_bar
      File "/home/ubuntu/venv/lib/python3.6/site-packages/pip/_internal/download.py", line 465, in unpack_url
        progress_bar=progress_bar
      File "/home/ubuntu/venv/lib/python3.6/site-packages/pip/_internal/download.py", line 316, in unpack_http_url
        progress_bar)
      File "/home/ubuntu/venv/lib/python3.6/site-packages/pip/_internal/download.py", line 551, in _download_http_url
        _download_url(resp, link, content_file, hashes, progress_bar)
      File "/home/ubuntu/venv/lib/python3.6/site-packages/pip/_internal/download.py", line 253, in _download_url
        hashes.check_against_chunks(downloaded_chunks)
      File "/home/ubuntu/venv/lib/python3.6/site-packages/pip/_internal/utils/hashes.py", line 80, in check_against_chunks
        for chunk in chunks:
      File "/home/ubuntu/venv/lib/python3.6/site-packages/pip/_internal/download.py", line 223, in written_chunks
        for chunk in chunks:
      File "/home/ubuntu/venv/lib/python3.6/site-packages/pip/_internal/download.py", line 212, in resp_read
        decode_content=False):
      File "/home/ubuntu/venv/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 564, in stream
        data = self.read(amt=amt, decode_content=decode_content)
      File "/home/ubuntu/venv/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 529, in read
        raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
      File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/ubuntu/venv/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 430, in _error_catcher
        raise ReadTimeoutError(self._pool, None, "Read timed out.")
    pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
    Traceback (most recent call last):
      File "/home/ubuntu/venv/lib/python3.6/site-packages/setuptools/installer.py", line 119, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/home/ubuntu/venv/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpykvyfq6f', '--quiet', 'cython>=0.27']' returned non-zero exit status 2.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-z5behrbg/yolo34py-gpu/setup.py", line 237, in <module>
        keywords="yolo darknet object detection vision",
      File "/home/ubuntu/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/home/ubuntu/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/ubuntu/venv/lib/python3.6/site-packages/setuptools/dist.py", line 721, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/ubuntu/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/home/ubuntu/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/home/ubuntu/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/home/ubuntu/venv/lib/python3.6/site-packages/setuptools/dist.py", line 777, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/home/ubuntu/venv/lib/python3.6/site-packages/setuptools/installer.py", line 121, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['/home/ubuntu/venv/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpykvyfq6f', '--quiet', 'cython>=0.27']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by madhawav** [comment]
This looks like a network connectivity issue.
