### ISSUE TITLE
Trouble installation from source

### ISSUE THREAD

**Issue by Rani-1234** [madhawav/YOLO3-4-Py#39]
Hi,
I'm following your instructions for installing from sources.

The only difference is that I'm using ubuntu 14.04 and a virtual env.

I got this error message while execute the command:
pip3 install .

x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -DUSE_GPU=0 -DUSE_CV=0 -I/home/rani-ubuntu/python-environments/darknet-python/lib/python3.5/site-packages/numpy/core/include -I/home/rani-ubuntu/Projects/yolo/darknet/include -I/home/rani-ubuntu/Projects/yolo/darknet/src -I/usr/include/python3.5m -I/home/rani-ubuntu/python-environments/darknet-python/include/python3.5m -c pydarknet.cpp -o build/temp.linux-x86_64-3.5/pydarknet.o

x86_64-linux-gnu-gcc: error: : No such file or directory

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

I have checked and all the path and files in the command exists.

any advice ?

**Comment by xeden3** [comment]
Me, neither

**Comment by madhawav** [comment]
Hi,
I will check on this and let you know.

**Comment by Guilmort** [comment]
Hi
Same for me in a python 3.7 virtualenv on Bionic Beaver(18.04LTS)
x86_64-linux-gnu-gcc returns error: : No such file or directory
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Any news about it ?

**Comment by Guilmort** [comment]
Hi
This happens when a lib is missing but there is not enough verbosity. Solved after having launched:
`DISTUTILS_DEBUG=1 pip3 install .`

Then I double checked my LD_CONFIG_PATH and PKG_CONFIG_PATH, correct them, correct line 77 include_paths variable by adding /opt/opencv/include path to (opencv includes when you have it installed in a non-standard location) and launched pip again and it worked!

**Comment by pherris** [comment]
@Guilmort perhaps you can help me divine the issue with my docker build - I added the `DISTUTILS_DEBUG` flag and have additional output but am unsure if I can isolate the problem from it.  I did try the suggested solution in another thread to `RUN python3 setup.py clean` - and while that doesn't fail to build, at runtime `pydarknet` cannot be found.  

For this trace, the command was `RUN pip3 install .`

```
Step 31/36 : RUN DISTUTILS_DEBUG=1 pip3 install .
 ---> Running in 4f39807db964
Processing /YOLO3-4-Py


Requirement already satisfied: cython>=0.27 in /usr/local/lib/python3.5/dist-packages (from yolo34py==0.1rc13) (0.29.1)
Collecting requests (from yolo34py==0.1rc13)
  Downloading https://files.pythonhosted.org/packages/ff/17/5cbb026005115301a8fb2f9b0e3e8d32313142fe8b617070e7baad20554f/requests-2.20.1-py2.py3-none-any.whl (57kB)
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from yolo34py==0.1rc13) (1.11.0)
Collecting urllib3<1.25,>=1.21.1 (from requests->yolo34py==0.1rc13)
  Downloading https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl (118kB)
Collecting certifi>=2017.4.17 (from requests->yolo34py==0.1rc13)
  Downloading https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl (154kB)
Collecting chardet<3.1.0,>=3.0.2 (from requests->yolo34py==0.1rc13)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
Collecting idna<2.8,>=2.5 (from requests->yolo34py==0.1rc13)
  Downloading https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl (58kB)
Building wheels for collected packages: yolo34py
  Running setup.py bdist_wheel for yolo34py: started
  Running setup.py bdist_wheel for yolo34py: finished with status 'error'
  Complete output from command /usr/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-n4btpg4d/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-91vvgld7 --python-tag cp35:
  WARNING:root:GPU environment variable is skipped since DARKNET_HOME is specified
  INFO:root:Compiling wrapper with OpenCV
  INFO:root:DARKNET_HOME is set: /darknet
  config vars:
  {'abiflags': 'm',
   'base': '/usr',
   'dist_fullname': 'UNKNOWN-0.0.0',
   'dist_name': 'UNKNOWN',
   'dist_version': '0.0.0',
   'exec_prefix': '/usr',
   'platbase': '/usr',
   'prefix': '/usr',
   'py_version': '3.5.2',
   'py_version_nodot': '35',
   'py_version_short': '3.5',
   'sys_exec_prefix': '/usr',
   'sys_prefix': '/usr',
   'userbase': '/root/.local',
   'usersite': '/root/.local/lib/python3.5/site-packages'}
  config vars:
  {'abiflags': 'm',
   'base': '/usr',
   'dist_fullname': 'UNKNOWN-0.0.0',
   'dist_name': 'UNKNOWN',
   'dist_version': '0.0.0',
   'exec_prefix': '/usr',
   'platbase': '/usr',
   'prefix': '/usr',
   'py_version': '3.5.2',
   'py_version_nodot': '35',
   'py_version_short': '3.5',
   'sys_exec_prefix': '/usr',
   'sys_prefix': '/usr',
   'userbase': '/root/.local',
   'usersite': '/root/.local/lib/python3.5/site-packages'}
  config vars:
  {'abiflags': 'm',
   'base': '/usr',
   'dist_fullname': 'UNKNOWN-0.0.0',
   'dist_name': 'UNKNOWN',
   'dist_version': '0.0.0',
   'exec_prefix': '/usr',
   'platbase': '/usr',
   'prefix': '/usr',
   'py_version': '3.5.2',
   'py_version_nodot': '35',
   'py_version_short': '3.5',
   'sys_exec_prefix': '/usr',
   'sys_prefix': '/usr',
   'userbase': '/root/.local',
   'usersite': '/root/.local/lib/python3.5/site-packages'}
  config vars:
  {'abiflags': 'm',
   'base': '/usr',
   'dist_fullname': 'UNKNOWN-0.0.0',
   'dist_name': 'UNKNOWN',
   'dist_version': '0.0.0',
   'exec_prefix': '/usr',
   'platbase': '/usr',
   'prefix': '/usr',
   'py_version': '3.5.2',
   'py_version_nodot': '35',
   'py_version_short': '3.5',
   'sys_exec_prefix': '/usr',
   'sys_prefix': '/usr',
   'userbase': '/root/.local',
   'usersite': '/root/.local/lib/python3.5/site-packages'}
  config vars:
  {'abiflags': 'm',
   'base': '/usr',
   'dist_fullname': 'UNKNOWN-0.0.0',
   'dist_name': 'UNKNOWN',
   'dist_version': '0.0.0',
   'exec_prefix': '/usr',
   'platbase': '/usr',
   'prefix': '/usr',
   'py_version': '3.5.2',
   'py_version_nodot': '35',
   'py_version_short': '3.5',
   'sys_exec_prefix': '/usr',
   'sys_prefix': '/usr',
   'userbase': '/root/.local',
   'usersite': '/root/.local/lib/python3.5/site-packages'}
  /usr/local/lib/python3.5/dist-packages/setuptools/dist.py:470: UserWarning: Normalizing '0.1.rc13' to '0.1rc13'
    normalized_version,
  options (after parsing config files):
  options (after parsing command line):
  option dict for 'aliases' command:
    {}
  option dict for 'bdist_wheel' command:
    {'dist_dir': ('command line', '/tmp/pip-wheel-91vvgld7'),
     'python_tag': ('command line', 'cp35')}
  running bdist_wheel
  Distribution.get_command_obj(): creating 'bdist_wheel' command object
    setting options for 'bdist_wheel' command:
      dist_dir = /tmp/pip-wheel-91vvgld7 (from command line)
      python_tag = cp35 (from command line)
  Distribution.get_command_obj(): creating 'bdist' command object
  Distribution.get_command_obj(): creating 'build' command object
  Distribution.get_command_obj(): creating 'build_scripts' command object
  running build
  INFO:root:Copying libdarknet.so from /darknet
  running build_py
  Distribution.get_command_obj(): creating 'build_py' command object
  INFO:root:Generating grammar tables from /usr/lib/python3.5/lib2to3/Grammar.txt
  INFO:root:Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
  creating build
  creating build/lib.linux-x86_64-3.5
  creating build/lib.linux-x86_64-3.5/__libdarknet
  copying __libdarknet/__init__.py -> build/lib.linux-x86_64-3.5/__libdarknet
  running egg_info
  Distribution.get_command_obj(): creating 'egg_info' command object
  creating yolo34py.egg-info
  writing requirements to yolo34py.egg-info/requires.txt
  writing dependency_links to yolo34py.egg-info/dependency_links.txt
  writing top-level names to yolo34py.egg-info/top_level.txt
  writing yolo34py.egg-info/PKG-INFO
  writing manifest file 'yolo34py.egg-info/SOURCES.txt'
  Distribution.get_command_obj(): creating 'build_ext' command object
  reading manifest file 'yolo34py.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  include __libdarknet/libdarknet.so
  include bridge.h
  include util.py
  include pydarknet.cpp
  warning: no files found matching 'pydarknet.cpp'
  include pypi_readme.md
  exclude_pattern: applying regex r'(^|\/)(RCS|CVS|\.svn)\/'
  writing manifest file 'yolo34py.egg-info/SOURCES.txt'
  copying __libdarknet/libdarknet.so -> build/lib.linux-x86_64-3.5/__libdarknet
  running build_ext
  cythoning pydarknet.pyx to pydarknet.cpp
  /usr/local/lib/python3.5/dist-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-req-build-n4btpg4d/pydarknet.pxd
    tree = Parsing.p_module(s, pxd, full_module_name)
  building 'pydarknet' extension
  creating build/temp.linux-x86_64-3.5
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DUSE_GPU=0 -DUSE_CV=1 -I/usr/lib/python3/dist-packages/numpy/core/include -I/darknet/include -I/darknet/src -I/usr/include/python3.5m -c pydarknet.cpp -o build/temp.linux-x86_64-3.5/pydarknet.o  -I/usr/local/include/opencv -I/usr/local/include
  x86_64-linux-gnu-gcc: error: : No such file or directory
  Traceback (most recent call last):
    File "/usr/lib/python3.5/distutils/unixccompiler.py", line 118, in _compile
      extra_postargs)
    File "/usr/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
      spawn(cmd, dry_run=self.dry_run)
    File "/usr/lib/python3.5/distutils/spawn.py", line 36, in spawn
      _spawn_posix(cmd, search_path, dry_run=dry_run)
    File "/usr/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
      % (cmd, exit_status))
  distutils.errors.DistutilsExecError: command ['x86_64-linux-gnu-gcc', '-pthread', '-DNDEBUG', '-g', '-fwrapv', '-O2', '-Wall', '-Wstrict-prototypes', '-g', '-fstack-protector-strong', '-Wformat', '-Werror=format-security', '-Wdate-time', '-D_FORTIFY_SOURCE=2', '-fPIC', '-DUSE_GPU=0', '-DUSE_CV=1', '-I/usr/lib/python3/dist-packages/numpy/core/include', '-I/darknet/include', '-I/darknet/src', '-I/usr/include/python3.5m', '-c', 'pydarknet.cpp', '-o', 'build/temp.linux-x86_64-3.5/pydarknet.o', '', '-I/usr/local/include/opencv -I/usr/local/include'] failed with exit status 1

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-n4btpg4d/setup.py", line 248, in <module>
      keywords="yolo darknet object detection vision",
    File "/usr/local/lib/python3.5/dist-packages/setuptools/__init__.py", line 143, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.5/dist-packages/wheel/bdist_wheel.py", line 188, in run
      self.run_command('build')
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-n4btpg4d/setup.py", line 170, in run
      build.run(self)
    File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-n4btpg4d/setup.py", line 175, in run
      build_ext.run(self)
    File "/usr/local/lib/python3.5/dist-packages/Cython/Distutils/old_build_ext.py", line 186, in run
      _build_ext.build_ext.run(self)
    File "/usr/lib/python3.5/distutils/command/build_ext.py", line 338, in run
      self.build_extensions()
    File "/usr/local/lib/python3.5/dist-packages/Cython/Distutils/old_build_ext.py", line 194, in build_extensions
      self.build_extension(ext)
    File "/usr/lib/python3.5/distutils/command/build_ext.py", line 532, in build_extension
      depends=ext.depends)
    File "/usr/lib/python3.5/distutils/ccompiler.py", line 574, in compile
      self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
    File "/usr/lib/python3.5/distutils/unixccompiler.py", line 120, in _compile
      raise CompileError(msg)
  distutils.errors.CompileError: command ['x86_64-linux-gnu-gcc', '-pthread', '-DNDEBUG', '-g', '-fwrapv', '-O2', '-Wall', '-Wstrict-prototypes', '-g', '-fstack-protector-strong', '-Wformat', '-Werror=format-security', '-Wdate-time', '-D_FORTIFY_SOURCE=2', '-fPIC', '-DUSE_GPU=0', '-DUSE_CV=1', '-I/usr/lib/python3/dist-packages/numpy/core/include', '-I/darknet/include', '-I/darknet/src', '-I/usr/include/python3.5m', '-c', 'pydarknet.cpp', '-o', 'build/temp.linux-x86_64-3.5/pydarknet.o', '', '-I/usr/local/include/opencv -I/usr/local/include'] failed with exit status 1

  ----------------------------------------
  Failed building wheel for yolo34py
  Running setup.py clean for yolo34py
Failed to build yolo34py
Installing collected packages: urllib3, certifi, chardet, idna, requests, yolo34py
config vars:
{'abiflags': 'm',
 'base': '/usr',
 'dist_fullname': 'urllib3-0.0.0',
 'dist_name': 'urllib3',
 'dist_version': '0.0.0',
 'exec_prefix': '/usr',
 'platbase': '/usr',
 'prefix': '/usr',
 'py_version': '3.5.2',
 'py_version_nodot': '35',
 'py_version_short': '3.5',
 'sys_exec_prefix': '/usr',
 'sys_prefix': '/usr',
 'userbase': '/root/.local',
 'usersite': '/root/.local/lib/python3.5/site-packages'}
config vars:
{'abiflags': 'm',
 'base': '/usr',
 'dist_fullname': 'certifi-0.0.0',
 'dist_name': 'certifi',
 'dist_version': '0.0.0',
 'exec_prefix': '/usr',
 'platbase': '/usr',
 'prefix': '/usr',
 'py_version': '3.5.2',
 'py_version_nodot': '35',
 'py_version_short': '3.5',
 'sys_exec_prefix': '/usr',
 'sys_prefix': '/usr',
 'userbase': '/root/.local',
 'usersite': '/root/.local/lib/python3.5/site-packages'}
config vars:
{'abiflags': 'm',
 'base': '/usr',
 'dist_fullname': 'chardet-0.0.0',
 'dist_name': 'chardet',
 'dist_version': '0.0.0',
 'exec_prefix': '/usr',
 'platbase': '/usr',
 'prefix': '/usr',
 'py_version': '3.5.2',
 'py_version_nodot': '35',
 'py_version_short': '3.5',
 'sys_exec_prefix': '/usr',
 'sys_prefix': '/usr',
 'userbase': '/root/.local',
 'usersite': '/root/.local/lib/python3.5/site-packages'}
config vars:
{'abiflags': 'm',
 'base': '/usr',
 'dist_fullname': 'idna-0.0.0',
 'dist_name': 'idna',
 'dist_version': '0.0.0',
 'exec_prefix': '/usr',
 'platbase': '/usr',
 'prefix': '/usr',
 'py_version': '3.5.2',
 'py_version_nodot': '35',
 'py_version_short': '3.5',
 'sys_exec_prefix': '/usr',
 'sys_prefix': '/usr',
 'userbase': '/root/.local',
 'usersite': '/root/.local/lib/python3.5/site-packages'}
config vars:
{'abiflags': 'm',
 'base': '/usr',
 'dist_fullname': 'requests-0.0.0',
 'dist_name': 'requests',
 'dist_version': '0.0.0',
 'exec_prefix': '/usr',
 'platbase': '/usr',
 'prefix': '/usr',
 'py_version': '3.5.2',
 'py_version_nodot': '35',
 'py_version_short': '3.5',
 'sys_exec_prefix': '/usr',
 'sys_prefix': '/usr',
 'userbase': '/root/.local',
 'usersite': '/root/.local/lib/python3.5/site-packages'}
  Running setup.py install for yolo34py: started
    Running setup.py install for yolo34py: finished with status 'error'
    Complete output from command /usr/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-n4btpg4d/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-xt8og27x/install-record.txt --single-version-externally-managed --compile:
    WARNING:root:GPU environment variable is skipped since DARKNET_HOME is specified
    INFO:root:Compiling wrapper with OpenCV
    INFO:root:DARKNET_HOME is set: /darknet
    /usr/local/lib/python3.5/dist-packages/setuptools/dist.py:470: UserWarning: Normalizing '0.1.rc13' to '0.1rc13'
      normalized_version,
    options (after parsing config files):
    options (after parsing command line):
    option dict for 'aliases' command:
      {}
    option dict for 'install' command:
      {'compile': ('command line', 1),
       'record': ('command line', '/tmp/pip-record-xt8og27x/install-record.txt'),
       'single_version_externally_managed': ('command line', 1)}
    running install
    Distribution.get_command_obj(): creating 'install' command object
      setting options for 'install' command:
        single_version_externally_managed = 1 (from command line)
        record = /tmp/pip-record-xt8og27x/install-record.txt (from command line)
        compile = 1 (from command line)
    config vars:
    {'abiflags': 'm',
     'base': '/usr',
     'dist_fullname': 'yolo34py-0.1rc13',
     'dist_name': 'yolo34py',
     'dist_version': '0.1rc13',
     'exec_prefix': '/usr',
     'platbase': '/usr',
     'prefix': '/usr',
     'py_version': '3.5.2',
     'py_version_nodot': '35',
     'py_version_short': '3.5',
     'sys_exec_prefix': '/usr',
     'sys_prefix': '/usr',
     'userbase': '/root/.local',
     'usersite': '/root/.local/lib/python3.5/site-packages'}
    Distribution.get_command_obj(): creating 'build' command object
    running build
    INFO:root:Copying libdarknet.so from /darknet
    running build_py
    Distribution.get_command_obj(): creating 'build_py' command object
    INFO:root:Generating grammar tables from /usr/lib/python3.5/lib2to3/Grammar.txt
    INFO:root:Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/__libdarknet
    copying __libdarknet/__init__.py -> build/lib.linux-x86_64-3.5/__libdarknet
    running egg_info
    Distribution.get_command_obj(): creating 'egg_info' command object
    writing requirements to yolo34py.egg-info/requires.txt
    writing yolo34py.egg-info/PKG-INFO
    writing top-level names to yolo34py.egg-info/top_level.txt
    writing dependency_links to yolo34py.egg-info/dependency_links.txt
    Distribution.get_command_obj(): creating 'build_ext' command object
    reading manifest file 'yolo34py.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    include __libdarknet/libdarknet.so
    include bridge.h
    include util.py
    include pydarknet.cpp
    warning: no files found matching 'pydarknet.cpp'
    include pypi_readme.md
    exclude_pattern: applying regex r'(^|\/)(RCS|CVS|\.svn)\/'
    writing manifest file 'yolo34py.egg-info/SOURCES.txt'
    copying __libdarknet/libdarknet.so -> build/lib.linux-x86_64-3.5/__libdarknet
    running build_ext
    cythoning pydarknet.pyx to pydarknet.cpp
    /usr/local/lib/python3.5/dist-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-req-build-n4btpg4d/pydarknet.pxd
      tree = Parsing.p_module(s, pxd, full_module_name)
    building 'pydarknet' extension
    creating build/temp.linux-x86_64-3.5
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DUSE_GPU=0 -DUSE_CV=1 -I/usr/lib/python3/dist-packages/numpy/core/include -I/darknet/include -I/darknet/src -I/usr/include/python3.5m -c pydarknet.cpp -o build/temp.linux-x86_64-3.5/pydarknet.o  -I/usr/local/include/opencv -I/usr/local/include
    x86_64-linux-gnu-gcc: error: : No such file or directory
    Traceback (most recent call last):
      File "/usr/lib/python3.5/distutils/unixccompiler.py", line 118, in _compile
        extra_postargs)
      File "/usr/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/lib/python3.5/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command ['x86_64-linux-gnu-gcc', '-pthread', '-DNDEBUG', '-g', '-fwrapv', '-O2', '-Wall', '-Wstrict-prototypes', '-g', '-fstack-protector-strong', '-Wformat', '-Werror=format-security', '-Wdate-time', '-D_FORTIFY_SOURCE=2', '-fPIC', '-DUSE_GPU=0', '-DUSE_CV=1', '-I/usr/lib/python3/dist-packages/numpy/core/include', '-I/darknet/include', '-I/darknet/src', '-I/usr/include/python3.5m', '-c', 'pydarknet.cpp', '-o', 'build/temp.linux-x86_64-3.5/pydarknet.o', '', '-I/usr/local/include/opencv -I/usr/local/include'] failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-n4btpg4d/setup.py", line 248, in <module>
        keywords="yolo darknet object detection vision",
      File "/usr/local/lib/python3.5/dist-packages/setuptools/__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.5/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.5/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-n4btpg4d/setup.py", line 170, in run
        build.run(self)
      File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-n4btpg4d/setup.py", line 175, in run
        build_ext.run(self)
      File "/usr/local/lib/python3.5/dist-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 338, in run
        self.build_extensions()
      File "/usr/local/lib/python3.5/dist-packages/Cython/Distutils/old_build_ext.py", line 194, in build_extensions
        self.build_extension(ext)
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 532, in build_extension
        depends=ext.depends)
      File "/usr/lib/python3.5/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/lib/python3.5/distutils/unixccompiler.py", line 120, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command ['x86_64-linux-gnu-gcc', '-pthread', '-DNDEBUG', '-g', '-fwrapv', '-O2', '-Wall', '-Wstrict-prototypes', '-g', '-fstack-protector-strong', '-Wformat', '-Werror=format-security', '-Wdate-time', '-D_FORTIFY_SOURCE=2', '-fPIC', '-DUSE_GPU=0', '-DUSE_CV=1', '-I/usr/lib/python3/dist-packages/numpy/core/include', '-I/darknet/include', '-I/darknet/src', '-I/usr/include/python3.5m', '-c', 'pydarknet.cpp', '-o', 'build/temp.linux-x86_64-3.5/pydarknet.o', '', '-I/usr/local/include/opencv -I/usr/local/include'] failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-n4btpg4d/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-xt8og27x/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-n4btpg4d/
```

**Comment by madhawav** [comment]
Hi all,
I have been quite busy with work. Sorry.

Is this issue solved?
