### ISSUE TITLE
Can't install yolo34py

### ISSUE THREAD

**Issue by martisaju** [madhawav/YOLO3-4-Py#79]
Hi, 
I am trying to install darknet by using pip install yolo34py and I get the following error:
`ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Marti\AppData\Local\Temp\pip-install-m_w_4b4c\yolo34py\setup.py", line 47, in <module>
        if USE_CV & (get_libs("opencv") == '' or get_cflags("opencv") == ''):
      File "C:\Users\Marti\AppData\Local\Temp\pip-install-m_w_4b4c\yolo34py\util.py", line 85, in get_libs
        proc = subprocess.Popen(shlex.split(command), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
      File "c:\users\marti\appdata\local\programs\python\python35-32\lib\subprocess.py", line 676, in __init__
        restore_signals, start_new_session)
      File "c:\users\marti\appdata\local\programs\python\python35-32\lib\subprocess.py", line 957, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\Marti\AppData\Local\Temp\pip-install-m_w_4b4c\yolo34py\`

Do you know how can I solve it? I extremely need this wrapper...

Thank you very much
Martí

**Comment by madhawav** [comment]
Hi, 
We don't support Windows currently, unfortunately.
