### ISSUE TITLE
Fatal Python error: Segmentation fault

### ISSUE THREAD

**Issue by bluesky1141** [madhawav/YOLO3-4-Py#88]
OS - raspbian(raspberry pi 3 B +)

I run 'python3 setup.py build_ext --inplace' and downloaded the weight as 'sh download_models.sh'
And I run the example through 'python3 webcam_demo.py', and I get a 'Fatal Python error: Segmentation fault'. What is the reason? Help me please!!

**Comment by mxmlnkn** [comment]
I also encounter a segfault in the line `net = pydark.Detector( ... )`. gdb shows:

```
#0  0x00007ffff63b0797 in free_network () from /home/maximiliank/.local/lib/python3.6/site-packages/__libdarknet/libdarknet.so
#1  0x00007ffff65e5707 in __pyx_pf_9pydarknet_8Detector_6__dealloc__ (__pyx_v_self=0x7ffff7ed3850) at pydarknet.cpp:3227
#2  __pyx_pw_9pydarknet_8Detector_7__dealloc__ (__pyx_v_self=0x7ffff7ed3850) at pydarknet.cpp:3212
#3  __pyx_tp_dealloc_9pydarknet_Detector (o=0x7ffff7ed3850) at pydarknet.cpp:5931
#4  0x00007ffff65ea91a in __pyx_tp_new_9pydarknet_Detector (t=<optimized out>, a=<optimized out>, k=<optimized out>) at pydarknet.cpp:5917
#5  0x00000000004db295 in ?? ()
#6  0x000000000045a0e3 in _PyObject_FastCallDict ()
#7  0x000000000054fd37 in ?? ()
#8  0x00000000005546cf in _PyEval_EvalFrameDefault ()
#9  0x000000000054fbe1 in ?? ()
#10 0x0000000000550b93 in PyEval_EvalCode ()
#11 0x000000000042b519 in PyRun_FileExFlags ()
#12 0x000000000042b705 in PyRun_SimpleFileExFlags ()
#13 0x0000000000441fcb in Py_Main ()
#14 0x0000000000421ff4 in main ()
```

I used `pip3 install --user opencv-python==3.4.0.14 cython numpy yolo34py` and executed the `download_model.sh` script.

**Comment by ebegen** [comment]
Is there any solution of this problem?

**Comment by madhawav** [comment]
Closing the issue due to inactivity. We do not officially support raspbian OS.
