### ISSUE TITLE
Unable to install yolo34py-gpu

### ISSUE THREAD

**Issue by cbroker1** [madhawav/YOLO3-4-Py#91]
Unable to install yolo34py-gpu 
(I apologize for the wall of text)
```
$ pip3 install yolo34py-gpu
Collecting yolo34py-gpu
  Using cached https://files.pythonhosted.org/packages/dc/a3/12c668e54109c5469a8312d757b357dda0b2efc2150043b76b58f6ba75c3/yolo34py-gpu-0.1rc12.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\carlb\appdata\local\programs\python\python36\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\carlb\\AppData\\Local\\Temp\\pip-install-798aonwf\\yolo34py-gpu\\setup.py'"'"'; __file__='"'"'C:\\Users\\carlb\\AppData\\Local\\Temp\\pip-install-798aonwf\\yolo34py-gpu\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\carlb\AppData\Local\Temp\pip-install-798aonwf\yolo34py-gpu\
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\carlb\AppData\Local\Temp\pip-install-798aonwf\yolo34py-gpu\setup.py", line 47, in <module>
        if USE_CV & (get_libs("opencv") == '' or get_cflags("opencv") == ''):
      File "C:\Users\carlb\AppData\Local\Temp\pip-install-798aonwf\yolo34py-gpu\util.py", line 85, in get_libs
        proc = subprocess.Popen(shlex.split(command), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
      File "c:\users\carlb\appdata\local\programs\python\python36\lib\subprocess.py", line 729, in __init__
        restore_signals, start_new_session)
      File "c:\users\carlb\appdata\local\programs\python\python36\lib\subprocess.py", line 1017, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
Prerequisites: 
Python version:
```
>>>import sys
>>>print(sys.version)
3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)]
```
Numpy, Cython, OpenCV:
```
$pip freeze
...
numpy==1.16.1
...
Cython==0.29.12
...
OpenCV-python==4.1.0.25
```
Cuda:
```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:04_Central_Daylight_Time_2018
Cuda compilation tools, release 10.0, V10.0.130
--
```
Thank you for reading.

**Comment by cbroker1** [comment]
Update: Found it it's not available on Windows.
